import Navbar from './components/Navbar'
import '../node_modules/bootstrap/dist/css/bootstrap.min.css'

export const metadata = {
  title: 'Mayowa Dev',
  description: 'Generated by create next app',
  keyword: 'web css , html'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <div className='container '>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  )
}
